# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0326325be1bca919cbbb431b0428a78f9c7d0f4979d1242015b8cfc9ae09bcb6e16071e372cfffca52c37d2aae6b474005c86ad89e2eff0a99e76110e3ebeb12
  
test:
  secret_key_base: 583656a683dc72c5464d7992a7140abba6e522a797b205e39f2ab604506410ce3684e70277320ddcd00609f3f5aedb2d47998b13c69f8914b00c0a91fe4110e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
